name: Continuous Integration
on: [push, pull_request]
jobs:
  Continous-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: ./gradlew build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: fatjars
          path: spark-osmpbf/build/libs
