name: Continuous Integration
on: [push, pull_request]
jobs:
  Continous-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: ./gradlew build
